### ISSUE TITLE
Optimzer playground optimizes the wrong HTML

### ISSUE THREAD

**Issue by morsssss** [ampproject/amp-toolbox#1214]
Forgive me if this is the wrong place to report this. But, I saw on [the npm toolbox-optimizer page](https://www.npmjs.com/package/@ampproject/toolbox-optimizer) that I could optimize an AMP page in [this glitch playground](https://toolbox-optimizer.glitch.me/)!

Unfortunately, whatever HTML I paste in the textarea, the glitch optimizes some sample HTML containing an `<amp-twitter>` - not my HTML.

**Comment by westonruter** [comment]
I see the same thing. 

I can see it is getting the input via `document.getElementById("input").value`. However, since CodeMirror is being used on the page, this underlying `textarea` isn't getting updated once a change is made. 

So instead of `input.value` it should be rather using `editor.getValue()`. Here's a remixed version that fixes that problem: https://fearless-potent-chamomile.glitch.me/

Remix: https://glitch.com/edit/#!/fearless-potent-chamomile

**Comment by sebastianbenz** [comment]
Fixed it (also fixed syntaxhighlighting). Thanks Ben and Weston for
looking into this!

>

**Comment by morsssss** [comment]
and thanks for the very quick fix!
