### ISSUE TITLE
[linter] `ViewportDisablesTapDelay` rule is too strict

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-toolbox#1268]
The rule currently performs a strict match for the viewport tag contents:

https://github.com/ampproject/amp-toolbox/blob/1c33cc793d3de7da89a6dbab0d57732cf874f292/packages/linter/src/rules/ViewportDisablesTapDelay.ts#L10-L14

AMP also recommends to include `minimum-scale=1` and `initial-scale=1`. ([docs](https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#vprt))

But because the rule does a strict match, it incorrectly flags viewport definitions like `<meta name="viewport" content="width=device-width,minimum-scale=1">`, which would not cause tap delay IIUC

**Comment by swissspidy** [comment]
Context: we're currently using `<meta name="viewport" content="width=device-width,minimum-scale=1">` in the Web Stories WordPress plugin.

https://github.com/ampproject/amp-wp/issues/5894 mentions that `initial-scale=1` causes tap delay. Is that also the case for `minimum-scale=1`?

cc @westonruter @sebastianbenz

**Comment by westonruter** [comment]
Audit originated in #980. I think check originated from this article: [300ms tap delay, gone away](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away).

But it may not be needed anymore as as the bug was closed in Chromium in April: https://bugs.chromium.org/p/chromium/issues/detail?id=1108987
