### ISSUE TITLE
[RuntimeVersion] https://cdn.ampproject.org/diversions no longer available

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#156]
We need to find a new way to determine the canary version. 

//cc @jridgewell

**Comment by jridgewell** [comment]
I'll be launching a dynamic `/rtv/metadata` within the next 2 weeks that will include all diversions.

```json
{
  "ampRuntimeVersion": "CURRENT_PROD",
  "ampCssUrl": "https://cdn.ampproject.org/rtv/CURRENT_PROD/v0.css",
  "canaryPercentage": "0.1",
  "diversions": [
    "CURRENT_OPTIN",
    "CURRENT_1%",
    "CURRENT_CONTROL"
  ]
}

**Comment by sebastianbenz** [comment]
@jridgewell perfect - thanks!

**Comment by jridgewell** [comment]
https://cdn.ampproject.org/rtv/metadata is live.

**Comment by sebastianbenz** [comment]
@jridgewell can you elaborate on what 

```
"diversions": [
    "CURRENT_OPTIN",
    "CURRENT_1%",
    "CURRENT_CONTROL"
  ]
```

means? Which one should a publisher use who is interested in testing the latest canary?

**Comment by jridgewell** [comment]
Opt-in is when you go to https://cdn.ampproject.org/experiments.html and toggle "dev-channel". It's the earliest possible time to get new code.

1% is the same code as opt-in that we're now comfortable releasing to 1% of the population.

Control is the same thing as production, but with a different URL. This is to compare experiments against, since prod's immutable caching would affect metrics.
