### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by MkVII** [ampproject/amp-toolbox#294]
Hi,

Ever since this library was updated yesterday, I've had errors whenever I try to deploy my code to Firebase.
Here is the full error message:

Function failed on loading user code. Error message: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/node_modules/amp-toolbox-core/lib/oneBehindFetch.js:30
async function oneBehindFetch(input, init) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/amp-toolbox-core/index.js:20:19)

This only started happening after the latest update. I wonder if anyone else is experiencing the same issue?

Thanks
Brad

**Comment by ithinkihaveacat** [comment]
The problem is that `amp-toolbox-core` 0.1.6 requires node 8.x for `async` support; 0.1.5 did not require this. ([Related `.travis.yml` change](https://github.com/ampproject/amp-toolbox/commit/e8bc8434011e7c2004f223b89909f4ceea29a6ab#diff-354f30a63fb0907d4ad57269548329e3).)

However, it looks like Firebase does support node 8, you just need to [specify it explicitly](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version). Does that work for you?

**Comment by MkVII** [comment]
Nice catch. Works fine now.

Argh, such a small change for the amount of time I spent trying to get this fixed haha.
Just for ease if other people experience this issue, you need to add the following to your package.json file:
"engines": {"node": "8"}

**Comment by sebastianbenz** [comment]
Thanks Michael for jumping in while I was OOO!
