### ISSUE TITLE
Bump version when support for older versions of node dropped?

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/amp-toolbox#295]
`amp-toolbox` 0.1.5 supported node 6; 0.1.6 supports 8+. This caused some confusion (see #294).

Perhaps bump at least the minor version of the package when the supported version of node changes?

**Comment by sebastianbenz** [comment]
Yeah, absolutely! I (accidentally) added breaking changes a lot earlier. I didn't notice because travis stopped running the tests since we switched to Lerna. After no-one else noticed this I thought it's safe not to make a major version bump...forgetting that this was dependent on the individual configurations  🤦‍♀️.
