### ISSUE TITLE
source of amp-toolbox-linter

### ISSUE THREAD

**Issue by ireinhart** [ampproject/amp-toolbox#296]
Hello,

where can I find the source of the npm package "amp-toolbox-linter" found at https://www.npmjs.com/package/amp-toolbox-linter?

We like to build a docker image of that package and would like to run it as a cronjob to do some checks at our site. Mainly "npx amp-toolbox-linter --force sxg https://www...."

I have some issues to understand the documentation at the npm package page. It is not clear to me, how can I install it as an executable binary. Or with npm cmd I have to use in witch directory.

Best,
Ingo

**Comment by ireinhart** [comment]
@ithinkihaveacat any hints?

**Comment by ithinkihaveacat** [comment]
Good question! The code is available at https://github.com/ithinkihaveacat/amp-toolbox/tree/amp-toolbox-linter, and there's a PR to get it into amp-toolbox properly at https://github.com/ampproject/amp-toolbox/pull/301 (not quite ready yet).

**Comment by ithinkihaveacat** [comment]
Re how to run it in a Docker container, `npx amp-toolbox-linter --force sxg $URL` will fetch the latest version every time you run it, so that might be suitable if you're not running it very frequently. `npm -g amp-toolbox-linter` will install an `amplint` binary in whatever location `npm` stashes global.

**Comment by ireinhart** [comment]
Thx for you input. The helpful hint was 'amplint' - found it in no docs. Now, I don't have to install it every time.
