### ISSUE TITLE
[linter] sxg vary header check should set an accept header

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#456]
The SXG vary header check should set an accept header.

```
> [vary] header is missing value [amp-cache-transform] [debug: curl -sS  -i -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' 'http://localhost:8080']
```

AMP Linter currently assumes that the vary header is set on a per URL basis. However, this is often hard to implement in a backend. For example, in the case of amp.dev we use the accept header to determine whether we set the vary header to AMP-Cache-Transform or not. 

The correct approach would be to check for the vary header only if both `text/html` and `application/signed-exchange` are present at the same time, because only if both are present we need to vary on the `amp-cache-transform` header (otherwise, `vary: accept` is sufficient for the CDN to differentiate the responses).

**Comment by sebastianbenz** [comment]
//cc @twifkak am I missing anything here?

**Comment by ithinkihaveacat** [comment]
This test is based on step (4) of https://github.com/ampproject/amppackager/blob/releases/README.md#productionizing. I think Google it, at least, uses the existence of vary: amp-cache-transform in the response (irrespective of request headers) to determine whether it should probe for SXG.

**Comment by twifkak** [comment]
@ithinkihaveacat Google no longer uses the `vary` header (as of 2018Q3 or so); the header is recommended only as a directive for CDNs to cache-key properly.

@sebastianbenz Short version is I understand if feasibility mandates a looser lint policy for now. Long version is there are lots of edge cases to worry about...

Ideally `vary: amp-cache-transform, accept` should appear on all responses for this URL (no matter the `accept` or `amp-cache-transform` request headers). e.g. If a user of a non-SXG browser visits page A and the CDN cache is populated with a non-SXG with no `vary`, will this prevent the crawler from later discovering the SXG?

It's unclear to me what a CDN cache should do if 1) non-SXG browser requests page A and response is non-SXG with `vary: accept`, and then 2) SXG browser requests page A and the response is non-SXG with `vary: accept, amp-cache-transform`, and then 3) SXG crawler requests page A. Will the updated `vary` from (2) allow the request (3) to pass through to origin, or will the original `vary` from (1) remain in the cache? What if the edge node that receives (2) is different from the node that receives (1) and (3)?

Conversely, what if 1) SXG crawler visits page and response is SXG with `vary: accept, amp-cache-transform`, and then 2) non-SXG browser visits and response is non-SXG with `vary: accept`, and then 3) SXG browser visits? Will the updated `vary` from (2) cause the request from (3) to mistakenly get the cached response from (1)?

https://cache-tests.fyi/#vary doesn't document these edge cases, it appears.

Anyway, that's a long way of saying, "Things will run smoother if we always have the right `vary` for the URL, or we disable caching." (But there's no way the linter could test for disabled caching, since you can't control which replica handles your request.)

**Comment by sebastianbenz** [comment]
Fair enough. "Things will run smoother if we always have the right vary for the URL" is probably the best general recommendation. 

In our case, Cloud CDN supports caching requests with `Vary` set to `Accept` and `Accept-Encoding`. Otherwise, the request won't get cached.

My thinking was:

`Accept: text/html` results in `Vary: Accept` => response will be cached
`Accept: text/html,application/sxg` results in `Vary: Accept;amp-cache-transform` => response will **not** be cached
`Accept: text/html;application/sxg amp-cache-transform: google;v="1"` results in `Vary: Accept;amp-cache-transform` => response will **not** be cached

The advantage would be that browsers not supporting sxg would at least get the benefit of edge caching.

**Comment by twifkak** [comment]
Ah, I see. Yeah, if Cloud CDN's behavior is to disable caching when `Vary` contains `amp-cache-transform`, then that seems like a reasonable approach to me. (Unless its `Accept` handling is too-clever-by-half and thinks its cached `text/html` would be good enough for SXG requestors. But I'm guessing that's not the case.) Thanks!

**Comment by ithinkihaveacat** [comment]
> Unless its Accept handling is too-clever-by-half and thinks its cached text/html would be good enough for SXG requestors.

I think this "too-clever-by-half" behavior is at least allowed: if you say you accept both `text/html` _and_ `application/sxg` (especially if no `q=` preference expressed), and the cache has an entry for the `text/html` variant, it seems totally legit for it to give it to you. (i.e. optimize based on the known semantics of `accept`, rather than just match strings.)

However, the Google Cloud CDN docs say they [don't perform this optimization](https://cloud.google.com/cdn/docs/caching#vary_headers), and it seems unlikely that any other cache does this sort of header normalization either. (Even the more common (?) normalization of `accept-language`, as [mentioned in the specs](https://tools.ietf.org/html/rfc7234#section-4.1) [doesn't seem to be implemented anywhere](https://cache-tests.fyi/#vary).)

So ultimately I'm happy to make this change though I'm OOO for the next few weeks and might not get to it before I get back so if someone else wants to do it please feel free.
