### ISSUE TITLE
FR: Make URL rewriting of SSR AMP component optional

### ISSUE THREAD

**Issue by mattwomple** [ampproject/amp-toolbox#515]
Feature Request

The `ampUrlPrefix` option for `ampOptimizer.transformHtml` supports rewriting all `cdn.ampproject.org` references to your own host. Some AMP components are actually server-side rendered, though. For example, if you fetch `https://cdn.ampproject.org/v0/amp-geo-0.1.js` in Spain, you get a different file than in the USA (easy to test with a VPN). Some "self-hosters" may not have the capability to do geolocation and determine what needs to update in server-side rendered JS.

It would be great if a new option could be introduced for `transformHtml`:
`rewriteSsrAmpUrls` that defaults to `true`, but could be set to `false` to preserve script URLs like `https://cdn.ampproject.org/v0/amp-geo-0.1.js` in the AMP document.

As far as I know `amp-geo` is the only component where SSR is used today. Having this option available would be beneficial to self-hosters who may not be able to keep up with the introduction of new SSR AMP components.

**Comment by ithinkihaveacat** [comment]
I think this only applies to `<amp-geo>`--it's the only component listed as having this behavior in the [AMP Cache Guidelines](https://github.com/ampproject/amphtml/blob/master/spec/amp-cache-guidelines.md#guidelines-adding-a-new-cache-to-the-amp-ecosystem).

Alos, this is bikeshedding, but I think a configuration key that avoids `ssr` would be preferable, since that's kinda overloaded already. Maybe `rewriteDynamicComponents`?

**Comment by mattwomple** [comment]
> Thanks for raising this (and starting the work)! I see one problem with this approach: AMP runtime and AMP extension versions might divert, which could cause unexpected problems.

Reasonable concern. The feature could be made to only work if `ampRuntimeVersion` is defined at time of transformation.
