### ISSUE TITLE
amp linter giving "Preview metadata is specified correctly" 

### ISSUE THREAD

**Issue by prash-mi** [ampproject/amp-toolbox#742]
amp linter (v2.3.0) is giving the following error on the page https://khabar.ndtv.com/webstories/entertainment/bollywood-actress-hit-in-acting-superhit-in-fashion-priyanka-chopra-deepika-105 

```
FAIL Preview metadata is specified correctly
> [poster-portrait-src = {"url":"https://c.ndtvimg.com/gws/105/assets/20.jpeg","width":696,"height":928,"mime":"image/webp"}] failed [isRaster]
```
(screenshot attached)
![amp lint](https://user-images.githubusercontent.com/11733935/80729276-a49c9f00-8b25-11ea-97ed-fe993734ac1e.png)

The specified poster-portrait-src seems to be having image/jpeg mime type and jpeg compression, screenshots:
`identify -verbose 20.jpeg `
![identify 20 jpeg](https://user-images.githubusercontent.com/11733935/80728720-e11bcb00-8b24-11ea-87b2-404c54fe3f86.png)

Content-type response header:
![mime type](https://user-images.githubusercontent.com/11733935/80729165-74550080-8b25-11ea-8433-d0061adab3e1.png)

Does it look like a bug or an issue with the specified poster-portrait-src ?

**Comment by ithinkihaveacat** [comment]
Thanks for the report! When that image is requested with a Googlebot user agent (and maybe others), it's delivered as  as WebP:

```sh
$ curl -sS -D - -o /dev/null -A 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' https://c.ndtvimg.com/gws/105/assets/20.jpeg
HTTP/2 200 
[...]
content-type: image/webp
```

The linter passes the Googlebot user agent, and currently doesn't accept WebP as a raster type. However, despite the format not being listed as an example of a raster type [in the documentation](https://amp.dev/documentation/components/amp-story/#poster-guidelines-(for-poster-portrait-src,-poster-landscape-src,-and-poster-square-src)), it does seem to be accepted. (At least by https://search.google.com/test/amp.)

I'll file a PR so that the linter allows WebP.
