### ISSUE TITLE
AMP Optimizer: provide a Cloudflare Webworker implementation

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp-toolbox#878]
[Cloudflare Webworkers](https://workers.cloudflare.com/) are potentially a simple way to integrate AMP Optimizer. We should provide a worker compatible version of AMP Optimizer. 

Current challenges are:

* We need to replace/disable all node specific dependencies (node-fetch, fs, ...) with browser compatible version. This can be done by providing a webworker specific configuration option.
* Provide a minified version that stays within the maximum worker size of 1MB.
* Make sure, optimization does stay within the execution time limit of 10/50ms. This might require disabling expensive transformations (CSS minification, extension auto import,...).

Related: @cramforce created a [working prototype](https://github.com/cramforce/amp-toolbox-optimizer-worker) some time ago, but since then we migrated from parse5 to htmlparser2. 

//cc @patrickkettner

**Comment by ithinkihaveacat** [comment]
Cloudflare just announced an "unbound" version of their workers that are less constrained re time (probably memory too):

https://blog.cloudflare.com/introducing-workers-unbound/

**Comment by sebastianbenz** [comment]
Excellent timing! This could be also really interesting for including image
optimization!

>

**Comment by dkolba** [comment]
Hey @sebastianbenz I just updated my app from AMP Optimizer 2.0.0, which was still able to run in a web worker (in the browser, I do not use Cloudflare), however, now a dependency (postcss et al.) introduced in 2.1.0 wants to use a node.js only API (fs).
My use case is creating valid AMP pages in the client without a server backend (which until 2.0.0 worked super smoothly btw). 

Instead of opting for Cloudflare Workers directly, would you please make web workers first class citizens. I think creating AMP in the client will become more popular in the future and doing expensive stuff like this in a web worker does not clog your process and web workers should be fully compatible with Cloudflare Workers.

Otherwise I would be stuck on V2.0 :|

**Comment by kesenwang** [comment]
Excited to see how this works out. Have a ghost blog and currently no option to use a AMP optimizer.

**Comment by samouri** [comment]
First draft design doc: https://docs.google.com/document/d/1Q5o4Y-HvxwrWLolyYIn7chDlaMi3BWzeL6pbturj7ic/edit#

**Comment by sebastianbenz** [comment]
https://github.com/ampproject/cloudflare-amp-optimizer 🎉
