### ISSUE TITLE
Problem with enable Blurry image placeholders

### ISSUE THREAD

**Issue by mjuzefiszyn** [ampproject/amp-toolbox#950]
We are trying to implement Blurry image placeholders, but we cannot see any changes. Our integration is developed through Lambda Egde.

The current configuration is:
`
const ampOptimizer = AmpOptimizer.create({
        preloadHeroImage: false,
        transformations: AmpOptimizer.TRANSFORMATIONS_PAIRED_AMP,
        blurredPlaceholders: true
});
`
It is running on the following [link](https://vader.news/.tests/ssr/noticia_0005.html)

Question: Currently not supported for valid AMP pages? We try to have it inline too, but it throws amp validation error. Any roadmap that is supported for valid amp?

Thanks!

**Comment by mjuzefiszyn** [comment]
Ticket update

We detected that in the [documentation](https://www.npmjs.com/package/amp-toolbox-optimizer/v/1.2.0-alpha.1) it had explicit _"This transforms requires install jimp and lru-cache: npm install jimp lru-cache"_

We install the requested dependencies _* note: the function developed in lambda had a weight of 7MB to 30MB with jimp and lru-cache_

On [this example](http://vader.news/.tests/ssr/noticia_0011.html) you can see the generated test, but even looking at the generated HTML the "i-amphtml-blurry-placeholder" we do not see the expected initial loading behavior of the placeholder

![WhatsApp Image 2020-11-17 at 15 28 03](https://user-images.githubusercontent.com/20131646/99455128-2ad3d380-2906-11eb-9ddc-4fdb565b994e.jpeg)

**Comment by jridgewell** [comment]
A few updates:

1. The `img.i-amphtml-blurry-placeholder`'s `src` isn't correct, because jimp failed to download the image. This is due to [Cloudflare WAF](https://www.cloudflare.com/lp/waf-x/) blocking requests that do not include a `User-Agent` request header.
2. The `amp-img` does not have an `i-amphtml-ssr` attribute, which is required for this to be valid transformed AMP
3. The `html` does not have an `amp` attribute, which is required for AMP format

The first is a publisher issue, but we could add a UA header to help out. The second is a genuine bug in the transformer. The third is because we're using `PAIRED_AMP` mode, and that doesn't output a valid transformed document.
